name: perform-tests
inputs:
  python-version:
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: ${{ inputs.python-version }}
        architecture: x64
    - name: Install Python dependencies of kas and tests
      shell: bash
      run: |
        # install kas to have all kas dependencies:
        pip install .[test]
    - name: Cache newt
      id: cache-newt
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: |
          newt
        key: cache-newt-${{ env.NEWT_REVISION }}
    - name: Install python-newt
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install libpopt-dev libslang2-dev gettext
        [ -d newt ] || git clone https://pagure.io/newt.git
        cd newt
        git checkout $NEWT_REVISION
        autoreconf -fi
        ./configure --with-python=python${{ matrix.python-version }}
        make -j $(nproc)
        sudo make install
        ln -s /usr/local/lib/python${{ matrix.python-version }}/site-packages/_snack.so \
              $(python3 -c 'import site; print(site.getsitepackages()[0])')/
        ln -s /usr/local/lib/python${{ matrix.python-version }}/site-packages/snack.py \
              $(python3 -c 'import site; print(site.getsitepackages()[0])')/
    - name: Run offline tests
      shell: bash
      env:
        TERM: xterm
        http_proxy: http://0.0.0.0:8118
        https_proxy: http://0.0.0.0:8118
      run: pytest -m "not online"
    - name: Run online tests
      shell: bash
      env:
        TERM: xterm
      run: pytest -m "online"
